**House_Rent Predication Model using Simple Linear Regression** ----> **Rent** is A Dependent Variable, **Size** is a Independent Variable.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [11]:
Dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/House-Size_Rent.csv')
Dataset['Rent (?/month)'] = Dataset['Rent (?/month)'].str.replace(',', '').astype(float)
Dataset

Size (sq.ft)  Rent (?/month)
0            450          6000.0
1            500          7000.0
2            550          7500.0
3            600          8500.0
4            650          9000.0
5            700         10000.0
6            750         11000.0
7            800         12000.0
8            850         12500.0
9            900         13500.0
10           950         14000.0
11          1000         15000.0
12          1050         15500.0
13          1100         16000.0
14          1150         17000.0
15          1200         18000.0
16          1250         18500.0
17          1300         19000.0
18          1350         20000.0
19          1400         21000.0

In [4]:
x = Dataset.iloc[:,:-1].values
x

array([[ 450],
       [ 500],
       [ 550],
       [ 600],
       [ 650],
       [ 700],
       [ 750],
       [ 800],
       [ 850],
       [ 900],
       [ 950],
       [1000],
       [1050],
       [1100],
       [1150],
       [1200],
       [1250],
       [1300],
       [1350],
       [1400]])

In [12]:
y = Dataset.iloc[:,1].values
y

array([ 6000.,  7000.,  7500.,  8500.,  9000., 10000., 11000., 12000.,
       12500., 13500., 14000., 15000., 15500., 16000., 17000., 18000.,
       18500., 19000., 20000., 21000.])

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[ 950],
       [1300],
       [ 750],
       [1100],
       [ 650],
       [ 550],
       [ 700],
       [1150],
       [ 900],
       [ 800],
       [1250],
       [1000],
       [ 600],
       [ 450],
       [1200],
       [1050]])

In [14]:
Lr = LinearRegression()
Lr.fit(x_train,y_train)

LinearRegression()

In [15]:
Lr.predict(x_test)

array([20150.35377358,  6939.26886792, 20927.47641509, 12379.12735849])

In [16]:
Lr.predict([[1450]])

array([21704.5990566])

In [19]:
# y = a + bx
Lr.coef_  #b


array([15.54245283])

In [20]:
Lr.intercept_ #a

np.float64(-831.9575471698099)

In [21]:
-831.9575471698099 + 15.54245283 * 1450

21704.59905633019

In [29]:
NewDataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/House-Size.csv')
NewDataset

Size (sq.ft)
0           1500
1           1550
2           1600
3           1650
4           1700
5           1750
6           1800
7           1850
8           1900
9           1950
10          2000

In [30]:
S = Lr.predict(NewDataset)
S

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([22481.72169811, 23258.84433962, 24035.96698113, 24813.08962264,
       25590.21226415, 26367.33490566, 27144.45754717, 27921.58018868,
       28698.70283019, 29475.8254717 , 30252.94811321])

In [32]:
df = pd.DataFrame(NewDataset) # Convert Array To Normal Form
df ["Rent (?/month)"] = S
df

Size (sq.ft)  Rent (?/month)
0           1500    22481.721698
1           1550    23258.844340
2           1600    24035.966981
3           1650    24813.089623
4           1700    25590.212264
5           1750    26367.334906
6           1800    27144.457547
7           1850    27921.580189
8           1900    28698.702830
9           1950    29475.825472
10          2000    30252.948113

In [33]:
df.to_csv('Predicated House_Rent.csv')
df.to_excel('Predicated House_Rent.xlsx')